ALTER TYPE "PropertyStatus" ADD VALUE IF NOT EXISTS 'EXPERT_OPINION_ORDERED';
ALTER TYPE "PropertyStatus" ADD VALUE IF NOT EXISTS 'EXPERT_OPINION_RECEIVED';
ALTER TYPE "PropertyStatus" ADD VALUE IF NOT EXISTS 'BINDING_OFFER_SENT';
ALTER TYPE "PropertyStatus" ADD VALUE IF NOT EXISTS 'BINDING_OFFER_ACCEPTED';

ALTER TABLE "properties"
  ADD COLUMN IF NOT EXISTS "indicative_offer_sent_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "expert_opinion_ordered_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "expert_opinion_received_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "binding_offer_sent_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "binding_offer_accepted_at" TIMESTAMP(3);
