ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'phone';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'website';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'referral';

ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'IN_REVIEW';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED_TO_PARTNER';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'PARTNER_CONTACT_PENDING';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONVERTED_TO_CASE';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CLOSED';

ALTER TABLE "leads"
  ADD COLUMN IF NOT EXISTS "mobile_phone" TEXT,
  ADD COLUMN IF NOT EXISTS "street" TEXT,
  ADD COLUMN IF NOT EXISTS "federal_state" TEXT,
  ADD COLUMN IF NOT EXISTS "preferred_contact_method" TEXT,
  ADD COLUMN IF NOT EXISTS "contact_consent" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "property_street" TEXT,
  ADD COLUMN IF NOT EXISTS "property_postal_code" TEXT,
  ADD COLUMN IF NOT EXISTS "property_city" TEXT,
  ADD COLUMN IF NOT EXISTS "living_area_sqm" INTEGER,
  ADD COLUMN IF NOT EXISTS "plot_area_sqm" INTEGER,
  ADD COLUMN IF NOT EXISTS "year_built" INTEGER,
  ADD COLUMN IF NOT EXISTS "property_note" TEXT,
  ADD COLUMN IF NOT EXISTS "region" TEXT,
  ADD COLUMN IF NOT EXISTS "routing_reason" TEXT,
  ADD COLUMN IF NOT EXISTS "internal_note" TEXT,
  ADD COLUMN IF NOT EXISTS "created_by_user_id" TEXT,
  ADD COLUMN IF NOT EXISTS "converted_case_id" TEXT;

ALTER TABLE "activities" ALTER COLUMN "property_id" DROP NOT NULL;
